/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as authenticatedCriarEmpresaRouteImport } from './routes/(authenticated)/criar-empresa'
import { Route as authenticatedhasCompanyRouteRouteImport } from './routes/(authenticated)/(has-company)/route'
import { Route as authenticatedhasCompanyProdutosRouteImport } from './routes/(authenticated)/(has-company)/produtos'
import { Route as authenticatedhasCompanyPlanosRouteImport } from './routes/(authenticated)/(has-company)/planos'
import { Route as authenticatedhasCompanyEmpresaRouteImport } from './routes/(authenticated)/(has-company)/empresa'
import { Route as authenticatedhasCompanyDashboardRouteImport } from './routes/(authenticated)/(has-company)/dashboard'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedCriarEmpresaRoute =
  authenticatedCriarEmpresaRouteImport.update({
    id: '/criar-empresa',
    path: '/criar-empresa',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedhasCompanyRouteRoute =
  authenticatedhasCompanyRouteRouteImport.update({
    id: '/(has-company)',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedhasCompanyProdutosRoute =
  authenticatedhasCompanyProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => authenticatedhasCompanyRouteRoute,
  } as any)
const authenticatedhasCompanyPlanosRoute =
  authenticatedhasCompanyPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => authenticatedhasCompanyRouteRoute,
  } as any)
const authenticatedhasCompanyEmpresaRoute =
  authenticatedhasCompanyEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => authenticatedhasCompanyRouteRoute,
  } as any)
const authenticatedhasCompanyDashboardRoute =
  authenticatedhasCompanyDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedhasCompanyRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-empresa': typeof authenticatedCriarEmpresaRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof authenticatedhasCompanyDashboardRoute
  '/empresa': typeof authenticatedhasCompanyEmpresaRoute
  '/planos': typeof authenticatedhasCompanyPlanosRoute
  '/produtos': typeof authenticatedhasCompanyProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-empresa': typeof authenticatedCriarEmpresaRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof authenticatedhasCompanyDashboardRoute
  '/empresa': typeof authenticatedhasCompanyEmpresaRoute
  '/planos': typeof authenticatedhasCompanyPlanosRoute
  '/produtos': typeof authenticatedhasCompanyProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/(has-company)': typeof authenticatedhasCompanyRouteRouteWithChildren
  '/(authenticated)/criar-empresa': typeof authenticatedCriarEmpresaRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/(authenticated)/(has-company)/dashboard': typeof authenticatedhasCompanyDashboardRoute
  '/(authenticated)/(has-company)/empresa': typeof authenticatedhasCompanyEmpresaRoute
  '/(authenticated)/(has-company)/planos': typeof authenticatedhasCompanyPlanosRoute
  '/(authenticated)/(has-company)/produtos': typeof authenticatedhasCompanyProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-empresa'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/empresa'
    | '/planos'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-empresa'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/empresa'
    | '/planos'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(authenticated)/(has-company)'
    | '/(authenticated)/criar-empresa'
    | '/_auth/login'
    | '/_auth/register'
    | '/(authenticated)/(has-company)/dashboard'
    | '/(authenticated)/(has-company)/empresa'
    | '/(authenticated)/(has-company)/planos'
    | '/(authenticated)/(has-company)/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/criar-empresa': {
      id: '/(authenticated)/criar-empresa'
      path: '/criar-empresa'
      fullPath: '/criar-empresa'
      preLoaderRoute: typeof authenticatedCriarEmpresaRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(has-company)': {
      id: '/(authenticated)/(has-company)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedhasCompanyRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(has-company)/produtos': {
      id: '/(authenticated)/(has-company)/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof authenticatedhasCompanyProdutosRouteImport
      parentRoute: typeof authenticatedhasCompanyRouteRoute
    }
    '/(authenticated)/(has-company)/planos': {
      id: '/(authenticated)/(has-company)/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof authenticatedhasCompanyPlanosRouteImport
      parentRoute: typeof authenticatedhasCompanyRouteRoute
    }
    '/(authenticated)/(has-company)/empresa': {
      id: '/(authenticated)/(has-company)/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof authenticatedhasCompanyEmpresaRouteImport
      parentRoute: typeof authenticatedhasCompanyRouteRoute
    }
    '/(authenticated)/(has-company)/dashboard': {
      id: '/(authenticated)/(has-company)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedhasCompanyDashboardRouteImport
      parentRoute: typeof authenticatedhasCompanyRouteRoute
    }
  }
}

interface authenticatedhasCompanyRouteRouteChildren {
  authenticatedhasCompanyDashboardRoute: typeof authenticatedhasCompanyDashboardRoute
  authenticatedhasCompanyEmpresaRoute: typeof authenticatedhasCompanyEmpresaRoute
  authenticatedhasCompanyPlanosRoute: typeof authenticatedhasCompanyPlanosRoute
  authenticatedhasCompanyProdutosRoute: typeof authenticatedhasCompanyProdutosRoute
}

const authenticatedhasCompanyRouteRouteChildren: authenticatedhasCompanyRouteRouteChildren =
  {
    authenticatedhasCompanyDashboardRoute:
      authenticatedhasCompanyDashboardRoute,
    authenticatedhasCompanyEmpresaRoute: authenticatedhasCompanyEmpresaRoute,
    authenticatedhasCompanyPlanosRoute: authenticatedhasCompanyPlanosRoute,
    authenticatedhasCompanyProdutosRoute: authenticatedhasCompanyProdutosRoute,
  }

const authenticatedhasCompanyRouteRouteWithChildren =
  authenticatedhasCompanyRouteRoute._addFileChildren(
    authenticatedhasCompanyRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedhasCompanyRouteRoute: typeof authenticatedhasCompanyRouteRouteWithChildren
  authenticatedCriarEmpresaRoute: typeof authenticatedCriarEmpresaRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedhasCompanyRouteRoute:
    authenticatedhasCompanyRouteRouteWithChildren,
  authenticatedCriarEmpresaRoute: authenticatedCriarEmpresaRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
